/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
public class BILLING extends javax.swing.JFrame {

    /**
     * Creates new form BILLING
     */
    public BILLING() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtcid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcustid = new javax.swing.JTextField();
        btnpaid = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtnod = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtk = new javax.swing.JTextField();
        btnpaid1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(9, 114, 209));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(9, 114, 209));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BOOKING ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jComboBox1.setBackground(new java.awt.Color(9, 114, 209));
        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setVerifyInputWhenFocusTarget(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, 223, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setBackground(new java.awt.Color(9, 114, 209));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CAB NO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 161, 32));

        txtcid.setEditable(false);
        txtcid.setBackground(new java.awt.Color(9, 114, 209));
        txtcid.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txtcid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 294, 32));

        jLabel4.setBackground(new java.awt.Color(9, 114, 209));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DRIVER ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 161, 35));

        txtdid.setEditable(false);
        txtdid.setBackground(new java.awt.Color(9, 114, 209));
        txtdid.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txtdid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtdid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 294, 35));

        jLabel5.setBackground(new java.awt.Color(9, 114, 209));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CUSTOMER ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 161, 35));

        txtcustid.setEditable(false);
        txtcustid.setBackground(new java.awt.Color(9, 114, 209));
        txtcustid.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txtcustid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtcustid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 294, 35));

        btnpaid.setBackground(new java.awt.Color(9, 114, 209));
        btnpaid.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnpaid.setForeground(new java.awt.Color(255, 255, 255));
        btnpaid.setText("PAID");
        btnpaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaidActionPerformed(evt);
            }
        });
        jPanel1.add(btnpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 116, 40));

        jButton2.setBackground(new java.awt.Color(9, 114, 209));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 116, 40));

        jLabel8.setBackground(new java.awt.Color(9, 114, 209));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NO OF DAYS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 161, 35));

        txtnod.setEditable(false);
        txtnod.setBackground(new java.awt.Color(9, 114, 209));
        txtnod.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txtnod.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtnod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 294, 35));

        jLabel9.setBackground(new java.awt.Color(9, 114, 209));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("FARE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 161, 35));

        txtf.setBackground(new java.awt.Color(9, 114, 209));
        txtf.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txtf.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 294, 35));

        jLabel10.setBackground(new java.awt.Color(9, 114, 209));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TRIP METER READING");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 161, 35));

        txtk.setBackground(new java.awt.Color(9, 114, 209));
        txtk.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txtk.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtk, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 294, 35));

        btnpaid1.setBackground(new java.awt.Color(9, 114, 209));
        btnpaid1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnpaid1.setForeground(new java.awt.Color(255, 255, 255));
        btnpaid1.setText("CALCULATE");
        btnpaid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaid1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnpaid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 116, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bigstock-Dead-tree-at-midnight-with-a-g-26565806.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 1, 560, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String choice =(String) jComboBox1.getSelectedItem();
    try
        {
            Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bmtt","root","mysql");
            Statement stmt = (Statement) con.createStatement();
            String bid =(String)jComboBox1.getSelectedItem();
            String hh = "select * from bookings where bid = "+bid;
            ResultSet rs1 = stmt.executeQuery(hh);
            rs1.first();
            txtcid.setText(rs1.getString("cid"));
            txtdid.setText(rs1.getString("did"));
            txtcustid.setText(rs1.getString("custid"));
            txtnod.setText(rs1.getString("nod"));
        }
    catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnpaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaidActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/bmtt","root","mysql");
            Statement stmt = conn.createStatement();
            String bid = (String)jComboBox1.getSelectedItem();
            String cid = txtcid.getText();
            String did = txtdid.getText();
            String custid = txtcustid.getText();
            
            String strSQL = "DELETE FROM BOOKINGS WHERE BID = " + bid + ";";
            String h1 = "update cabs set available = 'y' where cid ="+(cid)+";";
            String h2 = "update drivers set available = 'y' where did ="+(did)+";";
            String h3 = "update customers set book = 'n' where cust_id ="+(custid)+";";
            int rs1 = stmt.executeUpdate(h1);
            int rs2 = stmt.executeUpdate(h2);
            int rs3 = stmt.executeUpdate(h3);
            int rowsEffected = stmt.executeUpdate(strSQL);
            JOptionPane.showMessageDialog(this, "Operation successfully");
            System.out.println(rowsEffected + " rows effected");
            conn.close();

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnpaidActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new MAIN_FRAME().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         DefaultComboBoxModel cModel;
        cModel = (DefaultComboBoxModel) jComboBox1.getModel();
           try
        {
              Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bmtt","root","mysql");
            Statement stmt = (Statement) con.createStatement();
             String hc = "select * from bookings";
              ResultSet rs3 = stmt.executeQuery(hc);
             while (rs3.next())
            {
                 String bid = rs3.getString("bid");
                cModel.addElement(bid);              
            }  
        }
            catch(Exception e)
                     {
                      JOptionPane.showMessageDialog(this, e.getMessage());
                     }
    }//GEN-LAST:event_formWindowOpened

    private void btnpaid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaid1ActionPerformed
       double f, k, amt;
       f = Double.parseDouble(txtf.getText());
       k = Double.parseDouble(txtk.getText());
       amt = (f*k);
       javax.swing.JOptionPane.showMessageDialog(this, amt);
    }//GEN-LAST:event_btnpaid1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BILLING().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpaid;
    private javax.swing.JButton btnpaid1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtcustid;
    private javax.swing.JTextField txtdid;
    private javax.swing.JTextField txtf;
    private javax.swing.JTextField txtk;
    private javax.swing.JTextField txtnod;
    // End of variables declaration//GEN-END:variables
}
