/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the 
/**
 *
 * @author student
 */
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
public class CAB_CANCELLATION extends javax.swing.JFrame {

    /**
     * Creates new form CAB_CANCELLATION
     */
    public CAB_CANCELLATION() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdid = new javax.swing.JTextField();
        txtmob = new javax.swing.JTextField();
        txtidno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtcustid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(9, 114, 209));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(9, 114, 209));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BOOKING ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 137, 51));

        jLabel2.setBackground(new java.awt.Color(9, 114, 209));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("DRIVER ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 137, 51));

        jLabel3.setBackground(new java.awt.Color(9, 114, 209));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("FROM");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 137, 51));

        jLabel4.setBackground(new java.awt.Color(9, 114, 209));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setText("TO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 137, 51));

        txtdid.setEditable(false);
        txtdid.setBackground(new java.awt.Color(9, 114, 209));
        txtdid.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txtdid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtdid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 308, 40));

        txtmob.setEditable(false);
        txtmob.setBackground(new java.awt.Color(9, 114, 209));
        txtmob.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txtmob.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtmob, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 308, 40));

        txtidno.setEditable(false);
        txtidno.setBackground(new java.awt.Color(9, 114, 209));
        txtidno.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txtidno.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtidno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 308, 40));

        jLabel5.setBackground(new java.awt.Color(9, 114, 209));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setText("CAB ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 137, 51));

        txtcid.setEditable(false);
        txtcid.setBackground(new java.awt.Color(9, 114, 209));
        txtcid.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txtcid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 308, 40));

        jButton2.setBackground(new java.awt.Color(9, 114, 209));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 134, 44));

        jButton3.setBackground(new java.awt.Color(9, 114, 209));
        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 134, 44));

        jComboBox1.setBackground(new java.awt.Color(9, 114, 209));
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 308, 39));

        txtcustid.setEditable(false);
        txtcustid.setBackground(new java.awt.Color(9, 114, 209));
        txtcustid.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txtcustid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtcustid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 308, 40));

        jLabel6.setBackground(new java.awt.Color(9, 114, 209));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setText("CUSTOMER ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 137, 51));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cncl download.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 460, 340));

        jLabel8.setBackground(new java.awt.Color(9, 114, 209));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CAB CANCELLATION");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/bmtt","root","mysql");
            Statement stmt = con.createStatement();
            String bid = (String) jComboBox1.getSelectedItem();
            String cid = txtcid.getText();
            String did = txtdid.getText();
            String custid = txtcustid.getText();

            String strSQL = "DELETE FROM bookings WHERE bid = " +(bid)+ ";";
             String h1 = "update cabs set available = 'y' where cid ="+(cid)+ ";";
           String h2 = "update drivers set available = 'y' where did ="+(did)+ ";";
           String h3 = "update customers set book = 'n' where cust_id ="+(custid)+ ";";
           int rs1 = stmt.executeUpdate(h1);
           int rs2 = stmt.executeUpdate(h2);
           int rs3 = stmt.executeUpdate(h3);
            JOptionPane.showMessageDialog(this, "Record successfully deleted");
            int rowsEffected = stmt.executeUpdate(strSQL);
            System.out.println(rowsEffected + " rows effected");
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        new MAIN_FRAME().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String choice =(String) jComboBox1.getSelectedItem();

        try
        {
            Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bmtt","root","mysql");
            Statement stmt = (Statement) con.createStatement();
            String h1 = "select * from bookings where bid = "+choice;
            ResultSet rs1 = stmt.executeQuery(h1);
            rs1.first();
            String cid = rs1.getString("cid");
            String did = rs1.getString("did");
            String custid = rs1.getString("custid");
            String fr = rs1.getString("from_date");
            String to = rs1.getString("to_date");
            txtcid.setText(cid);
            txtdid.setText(did);
            txtcustid.setText(custid);
            txtmob.setText(fr);
            txtidno.setText(to);

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultComboBoxModel custModel;
        custModel = (DefaultComboBoxModel) jComboBox1.getModel();
           try
        {
              Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bmtt","root","mysql");
            Statement stmt = (Statement) con.createStatement();
             String hc = "select * from bookings";
              ResultSet rs3 = stmt.executeQuery(hc);
             while (rs3.next())
            {
                 String bid = rs3.getString("bid");
                custModel.addElement(bid);
            }  
        }
            catch(Exception e)
                     {
                      JOptionPane.showMessageDialog(this, e.getMessage());
                     }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAB_CANCELLATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAB_CANCELLATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAB_CANCELLATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAB_CANCELLATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CAB_CANCELLATION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtcustid;
    private javax.swing.JTextField txtdid;
    private javax.swing.JTextField txtidno;
    private javax.swing.JTextField txtmob;
    // End of variables declaration//GEN-END:variables
}
