/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.HeadlessException;
/**
 *
 * @author Rockstar_0901
 */import java.sql.*;
import javax.swing.JOptionPane;
public class CABS_INSERT extends javax.swing.JFrame {

    /**
     * Creates new form CABS_INSERT
     */
    public CABS_INSERT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnins = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(9, 114, 209));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnins.setBackground(new java.awt.Color(9, 114, 209));
        btnins.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnins.setForeground(new java.awt.Color(255, 255, 255));
        btnins.setText("INSERT");
        btnins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsActionPerformed(evt);
            }
        });
        jPanel1.add(btnins, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 105, 43));

        btnback.setBackground(new java.awt.Color(9, 114, 209));
        btnback.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 105, 43));

        jLabel1.setBackground(new java.awt.Color(9, 114, 209));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CABS INSERT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 320, 40));

        jLabel2.setBackground(new java.awt.Color(9, 114, 209));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 135, 49));

        jLabel3.setBackground(new java.awt.Color(9, 114, 209));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CAB REGN NO.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 135, 49));

        txtcid.setBackground(new java.awt.Color(9, 114, 209));
        txtcid.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtcid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 208, 38));

        txtname.setBackground(new java.awt.Color(9, 114, 209));
        txtname.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 208, 44));

        txtno.setBackground(new java.awt.Color(9, 114, 209));
        txtno.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtno.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 208, 41));

        jLabel5.setBackground(new java.awt.Color(9, 114, 209));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CAB ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 135, 49));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/20180129_165414.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsActionPerformed
          try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/bmtt","root","mysql");
            Statement stmt = con.createStatement();  
            String cname = txtname.getText();
            String cno = txtno.getText();
            String strSQL = "INSERT INTO cabs(cname, cno) VALUES ('"+(cname)+"','"+(cno)+"')";
            JOptionPane.showMessageDialog(this, "Record successfully inserted");
            int rowsEffected = stmt.executeUpdate(strSQL);
            System.out.println(rowsEffected + " rows effected");
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();
        } 
    }//GEN-LAST:event_btninsActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.setVisible(false);
        new MAIN_FRAME().setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/bmtt","root","mysql");
            Statement stmt = con.createStatement();  
           String strSQL = "SELECT ifnull(MAX(CID),0) FROM CABS";
              ResultSet rs = stmt.executeQuery(strSQL);     
             int cid = 0;
             if(rs.first())
             {
                 cid = rs.getInt(1);
                 cid++;
             }
            txtcid.setText(""+cid);
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();
        } 
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CABS_INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CABS_INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CABS_INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CABS_INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CABS_INSERT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtno;
    // End of variables declaration//GEN-END:variables
}
