

import javax.swing.JOptionPane;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class CUSTOMER_INSERT extends javax.swing.JFrame {

    /**
     * Creates new form customer_insert
     */
    public CUSTOMER_INSERT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcust_add = new javax.swing.JTextField();
        txtmobno = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtcustid = new javax.swing.JTextField();
        btnins = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtcust_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(9, 114, 209));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(9, 114, 209));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 129, 41));

        jLabel3.setBackground(new java.awt.Color(9, 114, 209));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 129, 41));

        jLabel4.setBackground(new java.awt.Color(9, 114, 209));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mobile No");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 129, 41));

        jLabel5.setBackground(new java.awt.Color(9, 114, 209));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Proof No");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 129, 41));

        txtcust_add.setBackground(new java.awt.Color(9, 114, 209));
        txtcust_add.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        txtcust_add.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtcust_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 397, 36));

        txtmobno.setBackground(new java.awt.Color(9, 114, 209));
        txtmobno.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        txtmobno.setForeground(new java.awt.Color(255, 255, 255));
        txtmobno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobnoActionPerformed(evt);
            }
        });
        jPanel1.add(txtmobno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 397, 36));

        txtid.setBackground(new java.awt.Color(9, 114, 209));
        txtid.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        txtid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 397, 36));

        txtcustid.setBackground(new java.awt.Color(9, 114, 209));
        txtcustid.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        txtcustid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtcustid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 397, 36));

        btnins.setBackground(new java.awt.Color(9, 114, 209));
        btnins.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btnins.setForeground(new java.awt.Color(255, 255, 255));
        btnins.setText("INSERT");
        btnins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsActionPerformed(evt);
            }
        });
        jPanel1.add(btnins, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 135, 44));

        jLabel6.setBackground(new java.awt.Color(9, 114, 209));
        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Light", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CUSTOMER INSERT");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 570, 64));

        btnback.setBackground(new java.awt.Color(9, 114, 209));
        btnback.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 126, 44));

        jLabel7.setBackground(new java.awt.Color(9, 114, 209));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Customer name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 129, 41));

        txtcust_name.setBackground(new java.awt.Color(9, 114, 209));
        txtcust_name.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        txtcust_name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtcust_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 397, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cus is.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 470, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmobnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobnoActionPerformed

    private void btninsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsActionPerformed
      try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/bmtt","root","mysql");
            Statement stmt = conn.createStatement();  
            String custname = txtcust_name.getText();
            String mobno = txtmobno.getText();
            String add = txtcust_add.getText();
            String idno = txtid.getText();
            String strSQL = "INSERT INTO customers(cust_name, address, mobile,id_no) VALUES ('"+(custname)+"','"+(add)+"','"+(mobno)+"','"+(idno)+"')";
            int rowsEffected = stmt.executeUpdate(strSQL);
            JOptionPane.showMessageDialog(this, "Record successfully inserted");
            System.out.println(rowsEffected + " rows effected");
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
               e.printStackTrace();
        }
    }//GEN-LAST:event_btninsActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
                        this.setVisible(false);
        new MAIN_FRAME().setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                 try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/bmtt","root","mysql");
            Statement stmt = con.createStatement();  
           String strSQL = "SELECT ifnull(MAX(Cust_ID),0) FROM CUSTOMERS";
              ResultSet rs = stmt.executeQuery(strSQL);     
             int custid = 0;
             if(rs.first())
             {
                 custid = rs.getInt(1);
                 custid++;
             }
            txtcustid.setText(""+custid);
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();
        } 
    }//GEN-LAST:event_formWindowOpened
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER_INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER_INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER_INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER_INSERT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CUSTOMER_INSERT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcust_add;
    private javax.swing.JTextField txtcust_name;
    private javax.swing.JTextField txtcustid;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmobno;
    // End of variables declaration//GEN-END:variables
}
