
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LOGIN.java
 *
 * Created on May 6, 2017, 11:55:46 PM
 */

/**
 *
 * @author admin
 */
public class LOGIN extends javax.swing.JFrame {

    /** Creates new form Login */
    public LOGIN() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        pwdfld = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btncls = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(9, 114, 209));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BLUE MOON TOURS AND TRAVELS");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(0, 0, 610, 70);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USER NAME");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(30, 120, 220, 40);

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(30, 250, 200, 40);

        txtuname.setFont(new java.awt.Font("Copperplate Gothic Light", 3, 18)); // NOI18N
        txtuname.setText("SREERAJ");
        jDesktopPane1.add(txtuname);
        txtuname.setBounds(330, 120, 190, 50);

        pwdfld.setEchoChar('*');
        jDesktopPane1.add(pwdfld);
        pwdfld.setBounds(330, 250, 190, 50);

        btnlogin.setBackground(new java.awt.Color(9, 54, 133));
        btnlogin.setFont(new java.awt.Font("Copperplate Gothic Light", 3, 18)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("LOGIN");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnlogin);
        btnlogin.setBounds(50, 380, 170, 50);

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Light", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SR INFOSYSTEMS LTD.®");
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(300, 440, 270, 50);

        btncls.setBackground(new java.awt.Color(9, 54, 133));
        btncls.setFont(new java.awt.Font("Copperplate Gothic Light", 3, 18)); // NOI18N
        btncls.setForeground(new java.awt.Color(255, 255, 255));
        btncls.setText("CLOSE");
        btncls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclsActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btncls);
        btncls.setBounds(350, 380, 170, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BLUE MOON.jpg"))); // NOI18N
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(120, 20, 370, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
     String username = txtuname.getText();
     String password = new String (pwdfld.getPassword());
     if (username.equals("SREERAJ")||username.equals("AASHISH"))
     {
         if(password.equals("123456"))
         {
             JOptionPane.showMessageDialog(null, "Access Granted!!");
         this.setVisible(false);
         new MAIN_FRAME().setVisible(true);
         }
         else
         {
             JOptionPane.showMessageDialog(null, "Incorrect Password!!");
             pwdfld.setText("");
         }
     }
     else
     {
         JOptionPane.showMessageDialog(null, "Access Denied!!");
         pwdfld.setText("");
         txtuname.setText("");
     }
}//GEN-LAST:event_btnloginActionPerformed

    private void btnclsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclsActionPerformed
         int conf = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?");
         if(conf == JOptionPane.YES_OPTION)
             System.exit(0);
         if(conf == JOptionPane.NO_OPTION)
             pwdfld.setText("");
    }//GEN-LAST:event_btnclsActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncls;
    private javax.swing.JButton btnlogin;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pwdfld;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables

}
